### ISSUE TITLE
week 4 npm scripts part 2

### ISSUE THREAD

**Issue by beingbing** [deltask/Coursera-Front-End-Web-UI-Frameworks-and-Tools#1]
hello,
sorry for this unwanted message but i too was attempting the course on full stack at coursera and got stuck on course 2 "Front-end-web-UI-frameworks-and-tools" week 4 npm scripts part 2, here i downloaded the "npm copyfiles package" but i was getting error that "copyfiles: not found" and while searching for the reason as why i am getting this error i stumbled on your repository but it didn't had package.json file uploaded so, if you have completed that exercise then can you please tell me that how you did it?
![screenshot from 2017-08-05 01 26 18](https://user-images.githubusercontent.com/26813160/28984862-9164b1aa-797d-11e7-9876-039436d25560.png)

**Comment by deltask** [comment]
The course has undergone syllabus changes during the past weeks.When I had completed the course npm scripts weren't  a part of the syllabus.We just had a brief introduction to npm and node.js.

But I might be able to help you if you can provide me with some additional details about this exercise that you had attempted.

**Comment by beingbing** [comment]
okay, i have shared a folder with you on google drive which contains the exercise at email id-
arjunsk1997@gmail.com
if this id is not in use then plz provide me your in-use email id.

**Comment by beingbing** [comment]
thanks for your time.
